// Generated by gencpp from file perception_stack_pkg/DetectedObject.msg
// DO NOT EDIT!


#ifndef PERCEPTION_STACK_PKG_MESSAGE_DETECTEDOBJECT_H
#define PERCEPTION_STACK_PKG_MESSAGE_DETECTEDOBJECT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace perception_stack_pkg
{
template <class ContainerAllocator>
struct DetectedObject_
{
  typedef DetectedObject_<ContainerAllocator> Type;

  DetectedObject_()
    : bbox_x1(0)
    , bbox_y1(0)
    , bbox_x2(0)
    , bbox_y2(0)
    , confidence(0.0)
    , class_id(0)
    , class_name()  {
    }
  DetectedObject_(const ContainerAllocator& _alloc)
    : bbox_x1(0)
    , bbox_y1(0)
    , bbox_x2(0)
    , bbox_y2(0)
    , confidence(0.0)
    , class_id(0)
    , class_name(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _bbox_x1_type;
  _bbox_x1_type bbox_x1;

   typedef int32_t _bbox_y1_type;
  _bbox_y1_type bbox_y1;

   typedef int32_t _bbox_x2_type;
  _bbox_x2_type bbox_x2;

   typedef int32_t _bbox_y2_type;
  _bbox_y2_type bbox_y2;

   typedef float _confidence_type;
  _confidence_type confidence;

   typedef int32_t _class_id_type;
  _class_id_type class_id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _class_name_type;
  _class_name_type class_name;





  typedef boost::shared_ptr< ::perception_stack_pkg::DetectedObject_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::perception_stack_pkg::DetectedObject_<ContainerAllocator> const> ConstPtr;

}; // struct DetectedObject_

typedef ::perception_stack_pkg::DetectedObject_<std::allocator<void> > DetectedObject;

typedef boost::shared_ptr< ::perception_stack_pkg::DetectedObject > DetectedObjectPtr;
typedef boost::shared_ptr< ::perception_stack_pkg::DetectedObject const> DetectedObjectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::perception_stack_pkg::DetectedObject_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::perception_stack_pkg::DetectedObject_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::perception_stack_pkg::DetectedObject_<ContainerAllocator1> & lhs, const ::perception_stack_pkg::DetectedObject_<ContainerAllocator2> & rhs)
{
  return lhs.bbox_x1 == rhs.bbox_x1 &&
    lhs.bbox_y1 == rhs.bbox_y1 &&
    lhs.bbox_x2 == rhs.bbox_x2 &&
    lhs.bbox_y2 == rhs.bbox_y2 &&
    lhs.confidence == rhs.confidence &&
    lhs.class_id == rhs.class_id &&
    lhs.class_name == rhs.class_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::perception_stack_pkg::DetectedObject_<ContainerAllocator1> & lhs, const ::perception_stack_pkg::DetectedObject_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace perception_stack_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::perception_stack_pkg::DetectedObject_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_stack_pkg::DetectedObject_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception_stack_pkg::DetectedObject_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception_stack_pkg::DetectedObject_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_stack_pkg::DetectedObject_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_stack_pkg::DetectedObject_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::perception_stack_pkg::DetectedObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "59ad9b3bc0b10f30a1f81dc9d89f08f9";
  }

  static const char* value(const ::perception_stack_pkg::DetectedObject_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x59ad9b3bc0b10f30ULL;
  static const uint64_t static_value2 = 0xa1f81dc9d89f08f9ULL;
};

template<class ContainerAllocator>
struct DataType< ::perception_stack_pkg::DetectedObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "perception_stack_pkg/DetectedObject";
  }

  static const char* value(const ::perception_stack_pkg::DetectedObject_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::perception_stack_pkg::DetectedObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 bbox_x1\n"
"int32 bbox_y1\n"
"int32 bbox_x2\n"
"int32 bbox_y2\n"
"float32 confidence\n"
"int32 class_id\n"
"string class_name\n"
;
  }

  static const char* value(const ::perception_stack_pkg::DetectedObject_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::perception_stack_pkg::DetectedObject_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.bbox_x1);
      stream.next(m.bbox_y1);
      stream.next(m.bbox_x2);
      stream.next(m.bbox_y2);
      stream.next(m.confidence);
      stream.next(m.class_id);
      stream.next(m.class_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DetectedObject_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::perception_stack_pkg::DetectedObject_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::perception_stack_pkg::DetectedObject_<ContainerAllocator>& v)
  {
    s << indent << "bbox_x1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.bbox_x1);
    s << indent << "bbox_y1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.bbox_y1);
    s << indent << "bbox_x2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.bbox_x2);
    s << indent << "bbox_y2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.bbox_y2);
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
    s << indent << "class_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.class_id);
    s << indent << "class_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.class_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PERCEPTION_STACK_PKG_MESSAGE_DETECTEDOBJECT_H
