// Generated by gencpp from file perception_stack_pkg/ObjectSpeed.msg
// DO NOT EDIT!


#ifndef PERCEPTION_STACK_PKG_MESSAGE_OBJECTSPEED_H
#define PERCEPTION_STACK_PKG_MESSAGE_OBJECTSPEED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace perception_stack_pkg
{
template <class ContainerAllocator>
struct ObjectSpeed_
{
  typedef ObjectSpeed_<ContainerAllocator> Type;

  ObjectSpeed_()
    : id(0)
    , speed(0.0)  {
    }
  ObjectSpeed_(const ContainerAllocator& _alloc)
    : id(0)
    , speed(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef float _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::perception_stack_pkg::ObjectSpeed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::perception_stack_pkg::ObjectSpeed_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectSpeed_

typedef ::perception_stack_pkg::ObjectSpeed_<std::allocator<void> > ObjectSpeed;

typedef boost::shared_ptr< ::perception_stack_pkg::ObjectSpeed > ObjectSpeedPtr;
typedef boost::shared_ptr< ::perception_stack_pkg::ObjectSpeed const> ObjectSpeedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::perception_stack_pkg::ObjectSpeed_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::perception_stack_pkg::ObjectSpeed_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::perception_stack_pkg::ObjectSpeed_<ContainerAllocator1> & lhs, const ::perception_stack_pkg::ObjectSpeed_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.speed == rhs.speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::perception_stack_pkg::ObjectSpeed_<ContainerAllocator1> & lhs, const ::perception_stack_pkg::ObjectSpeed_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace perception_stack_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::perception_stack_pkg::ObjectSpeed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_stack_pkg::ObjectSpeed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception_stack_pkg::ObjectSpeed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception_stack_pkg::ObjectSpeed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_stack_pkg::ObjectSpeed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_stack_pkg::ObjectSpeed_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::perception_stack_pkg::ObjectSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "69153bf8feb56938b0d6359bb63bbc1b";
  }

  static const char* value(const ::perception_stack_pkg::ObjectSpeed_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x69153bf8feb56938ULL;
  static const uint64_t static_value2 = 0xb0d6359bb63bbc1bULL;
};

template<class ContainerAllocator>
struct DataType< ::perception_stack_pkg::ObjectSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "perception_stack_pkg/ObjectSpeed";
  }

  static const char* value(const ::perception_stack_pkg::ObjectSpeed_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::perception_stack_pkg::ObjectSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 id\n"
"float32 speed\n"
;
  }

  static const char* value(const ::perception_stack_pkg::ObjectSpeed_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::perception_stack_pkg::ObjectSpeed_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectSpeed_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::perception_stack_pkg::ObjectSpeed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::perception_stack_pkg::ObjectSpeed_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PERCEPTION_STACK_PKG_MESSAGE_OBJECTSPEED_H
